name: 'Phalcon PHP extension build action'
description: 'Build Phalcon Framework for Linux according to various PHP versions.'

inputs:
  pecl:
    description: 'PECL package path'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Build Phalcon for Linux'
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        ls -lah
        export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
        sudo pecl -v install ${{ inputs.pecl }}

    - name: Check Extension
      shell: bash
      run: php --ri phalcon
