name: Stubs Generation

on:
  workflow_call:
    inputs:
      extensions:
        description: 'PHP extensions which must be installed for current PHP version.'
        type: string
        required: true
#      psr-version:
#        required: true
#        type: string
#      ZEPHIR_PARSER_VERSION:
#        required: true
#        type: string


jobs:
  stubs:
    name: Stubs validation for PHP ${{ matrix.php }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl
          extensions: ${{ inputs.extensions }}
          # psr-${{ github.event.inputs.psr-version }}, zephir_parser-${{ inputs.ZEPHIR_PARSER_VERSION }}

      - name: Install System Dependencies
        run: |
          sudo apt update --quiet --yes 1>/dev/null
          sudo apt install --no-install-recommends -q -y re2c

      - run: composer install --prefer-dist

      - name: Install Zephir
        run: .ci/install-zephir.sh

      - name: Validate stubs
        if: always()
        run: |
          $HOME/bin/zephir stubs
          vendor/bin/psalm ide/
